stages:
  - testsuite

.php7:
  stage: testsuite
  script:
    - pecl install vld-beta
    - rm -rf src/tests/*php8*/
    - make tests
  after_script:
    - grep -r . ./src/tests/*/*.out
    - grep -r . ./src/tests/*/*.diff

.php8:
  stage: testsuite
  script:
    - make tests
  after_script:
    - grep -r . ./src/tests/*/*.out
    - grep -r . ./src/tests/*/*.diff

testsuite:php7.0:
  extends: .php7
  image: php:7.0

testsuite:php7.1:
  extends: .php7
  image: php:7.1

testsuite:php7.2:
  extends: .php7
  image: php:7.2

testsuite:php7.3:
  extends: .php7
  image: php:7.3

testsuite:php7.4:
  extends: .php7
  image: php:7.3

testsuite:php8.0:
  extends: .php8
  image: php:8.0

## Operating system images

testsuite:debian:
  extends: .php7
  image: debian:stable
  before_script:
    - apt update
    - apt install -y php-dev
