stages:
  - testsuite

testsuite:debian:
  image: debian
  stage: testsuite
  script:
    - apt-get -qqy update
    - apt-get -qqy install --no-install-recommends php-dev gcc make
    - make debug

testsuite:fedora:
  image: fedora
  stage: testsuite
  script:
    - dnf install -y php-devel gcc make
    - make debug

testsuite:ubuntu:
  image: ubuntu
  stage: testsuite
  script:
    - apt-get -qqy update
    - DEBIAN_FRONTEND=noninteractive apt-get -qqy install --no-install-recommends php-dev gcc make
    - make debug

testsuite:alpine:
  image: alpine
  stage: testsuite
  script:
    - apk update
    - apk add php7-dev make gcc musl-dev
    - make compile_debug
    - TEST_PHP_ARGS='-q' REPORT_EXIT_STATUS=1 make -C src test TESTS="tests/cookies_encryption tests/deny_writable tests/disable_function"
    - TEST_PHP_ARGS='-q' REPORT_EXIT_STATUS=1 make -C src test TESTS="test/dump_request tests/eval_blacklist tests/global_strict"
    - TEST_PHP_ARGS='-q' REPORT_EXIT_STATUS=1 make -C src test TESTS="tests/harden_rand tests/sloppy_comparison tests/stream_wrappers"
    - TEST_PHP_ARGS='-q' REPORT_EXIT_STATUS=1 make -C src test TESTS="tests/unserialize tests/xxe"
