name: CI for php versions
on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          container:
            - php:8.4-rc
            - php:8.3
            - php:8.2
            - php:8.1
            - php:8.0
            - php:7.4
            - php:7.3
            - php:7.2
            - php:7.1
    container: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: PHP 7 env setup
        if: startsWith(matrix.container, 'php:7')
        run: |
          pecl install vld-beta
          rm -rf src/tests/*php8*/ src/tests/*/*_php8.phpt
      - name: Build and run the testsuite
        run: |
          make release
          ln -s $(php -r 'echo ini_get("extension_dir");')/* src/modules/
          rm -f src/tests/disable_function/*_signal.phpt
          make tests
      - name: Show logs in case of failure
        if: ${{ failure() }}
        run: |
          grep -r . --include='*.log' src/tests
