name: CI for linux distributions on PHP7
on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'


jobs:
  debian:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Remove php8 tests for php7
        run: rm -rf src/tests/*php8*/ src/tests/*/*_php8.phpt src/tests/disable_function/*_signal.phpt
      - name: Install dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y php-dev php-pear re2c
      - name: Install pecl
        run: pecl install vld-beta
      - name: Build and run the testsuite
        run: make release tests
      - name: Show logs in case of failure
        if: ${{ failure() }}
        run: |
          grep -r . --include='*.log' src/tests

  fedora:
    runs-on: ubuntu-latest
    container: fedora:34
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Remove php8 tests for php7
        run: rm -rf src/tests/*php8*/ src/tests/*/*_php8.phpt src/tests/disable_function/*_signal.phpt
      - name: Install dependencies
        run: |
          dnf install -y php-devel php-pear make re2c
      - name: Install pecl
        run: pecl install vld-beta
      - name: Build and run the testsuite
        run: make release tests
      - name: Show logs in case of failure
        if: ${{ failure() }}
        run: |
          grep -r . --include='*.log' src/tests

  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Remove php8 tests for php7
        run: rm -rf src/tests/*php8*/ src/tests/*/*_php8.phpt
      - name: Install dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y php-dev
      - name: Install pecl
        run: pecl install vld-beta
      - name: Build and run the testsuite
        run: make tests
      - name: Show logs in case of failure
        if: ${{ failure() }}
        run: |
          grep -r . --include='*.log' src/tests
